//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtimeViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealtimeViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (指紋認証してください) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BeforeAuthoricationUserName {
            get {
                return ResourceManager.GetString("BeforeAuthoricationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cam_flip_h_24 {
            get {
                object obj = ResourceManager.GetObject("cam_flip_h_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cam_flip_hv_24 {
            get {
                object obj = ResourceManager.GetObject("cam_flip_hv_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cam_flip_v_24 {
            get {
                object obj = ResourceManager.GetObject("cam_flip_v_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap cam_normal_24 {
            get {
                object obj = ResourceManager.GetObject("cam_normal_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   緊急通報モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmergencyMode {
            get {
                return ResourceManager.GetString("EmergencyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンジニアモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EngineerMode {
            get {
                return ResourceManager.GetString("EngineerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ic_error_red_24dp {
            get {
                object obj = ResourceManager.GetObject("ic_error_red_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap ic_warning_amber_24dp {
            get {
                object obj = ResourceManager.GetObject("ic_warning_amber_24dp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon livegps {
            get {
                object obj = ResourceManager.GetObject("livegps", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Gセンサー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MovieType0 {
            get {
                return ResourceManager.GetString("MovieType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   衝突 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MovieType1 {
            get {
                return ResourceManager.GetString("MovieType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドラレコ映像 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MovieType2 {
            get {
                return ResourceManager.GetString("MovieType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   緊急 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MovieType3 {
            get {
                return ResourceManager.GetString("MovieType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   認証無しモード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoAuthMode {
            get {
                return ResourceManager.GetString("NoAuthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon ship {
            get {
                object obj = ResourceManager.GetObject("ship", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   配信終了をリクエストしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamingEndRequest {
            get {
                return ResourceManager.GetString("StreamingEndRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信情報を取得中です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamingInfoGet {
            get {
                return ResourceManager.GetString("StreamingInfoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信を視聴中です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamingNow {
            get {
                return ResourceManager.GetString("StreamingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リクエストを再送しています... [{0}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamingRestartRequestFormat {
            get {
                return ResourceManager.GetString("StreamingRestartRequestFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配信開始をリクエストしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StreamingStartRequest {
            get {
                return ResourceManager.GetString("StreamingStartRequest", resourceCulture);
            }
        }
    }
}
